<?
    $this->headTitle('ElFinder');
    $this->headLink()
        ->prependStylesheet($this->basePath($BasePath) . '/css/theme.css')
        ->prependStylesheet($this->basePath($BasePath) . '/css/elfinder.min.css')
        ->prependStylesheet($this->basePath($BasePath) . '/jquery/ui-themes/smoothness/jquery-ui-1.8.23.custom.css')
    ;
    $this->headScript()
        // Select language
        ->prependFile($this->basePath($BasePath) . '/js/i18n/elfinder.ca.js', 'text/javascript')
        ->prependFile($this->basePath($BasePath) . '/js/elfinder.min.js', 'text/javascript')
        ->prependFile($this->basePath($BasePath) . '/jquery/jquery-ui-1.8.23.custom.min.js', 'text/javascript')
        ->prependFile($this->basePath($BasePath) . '/jquery/jquery-1.8.1.min.js', 'text/javascript')
    ;
?>

<div class="row-fluid">
    <div class="span12">
        <h1>Elfinder</h1>
        <div id="elfinder"></div>
    </div>
</div>
<script type="text/javascript">


    $('#elfinder').elfinder({
        url : '<?php echo $ConnectorPath?>',
        // Select language with exist in library
        lang : 'fr',
        height:'500'
    }).elfinder('instance');

</script>
<?php echo $ConnectorPath?>