<?php
//facebook application configuration
$fbconfig['appid' ] = "118474821657382";
$fbconfig['secret'] = "fde26982baea07cab11881876a45a5fe";
$fbconfig['baseUrl'] = "http://playground.local/facebook/"; //canvas URL;
$fbconfig['appBaseUrl'] = "http://apps.facebook.com/adfab_playground"; //facebook URL;
/*
 * If user first time authenticated the application facebook
* redirects user to baseUrl, so I checked if any code passed
* then redirect him to the application url
*/

if (isset($_GET['code'])){
    header("Location: " . $fbconfig['appBaseUrl']);
    exit;
}
if (isset($_GET['request_ids'])){
    //user comes from invitation
    //track them if you need
}

$user = null; //facebook user uid
/*try{
    include_once "src/facebook.php";
}
catch(Exception $o){
    echo '<pre>';
    print_r($o);
    echo '</pre>';
}
*/
// Create our Application instance.
$facebook = new \Facebook(array(
        'appId' => $fbconfig['appid'],
        'secret' => $fbconfig['secret'],
        'cookie' => true,
));//Facebook Authentication part

$user = $facebook->getUser();

// We may or may not have this data based
// on whether the user is logged in.
// If we have a $user id here, it means we know
// the user is logged into
// Facebook, but we don’t know if the access token is valid. An access
// token is invalid if the user logged out of Facebook.

$loginUrl = $facebook->getLoginUrl(
    array(
        'scope' => 'email'
    )
);

if ($user) {
    try {
        // Proceed knowing you have a logged in user who's authenticated.
        $user_profile = $facebook->api('/me');
        $access_token = $facebook->getAccessToken();
    } catch (FacebookApiException $e) {
        //you should use error_log($e); instead of printing the info on browser
        d($e); // d is a debug function defined at the end of this file
        $user = null;
    }
}

if (!$user) {
    echo "<script type='text/javascript'>top.location.href = '$loginUrl';</script>";
    exit;
}

echo $user_profile['name'];

?>
