<h1>Onglet3</h1>

<?php

$fbconfig['appid' ]     = "218054684985857";
$fbconfig['secret']     = "efa396557e4ced4c6b8e5dcf83cbef1f";
$fbconfig['baseUrl']    = "http://playground.local/facebook/onglet3/"; //canvas URL;
$fbconfig['appBaseUrl'] = "http://www.facebook.com/pages/FB-Dev/330253093762158?sk=app_218054684985857"; //facebook URL;

/*
 * If user first time authenticated the application facebook
 * redirects user to baseUrl, so I checked if any code passed
 * then redirect him to the application url
 */

if (isset($_GET['code'])){
    header("Location: " . $fbconfig['appBaseUrl']);
    exit;
}
if (isset($_GET['request_ids'])){
    //user comes from invitation
    //track them if you need
}

$user = null; //facebook user uid
/*try{
    include_once "src/facebook.php";
}
catch(Exception $o){
    echo '<pre>';
    print_r($o);
    echo '</pre>';
}
*/
// Create our Application instance.
$facebook = new \Facebook(array(
        'appId' => $fbconfig['appid'],
        'secret' => $fbconfig['secret'],
        'cookie' => true,
));//Facebook Authentication part

$user = $facebook->getUser();

// We may or may not have this data based
// on whether the user is logged in.
// If we have a $user id here, it means we know
// the user is logged into
// Facebook, but we don’t know if the access token is valid. An access
// token is invalid if the user logged out of Facebook.

$loginUrl = $facebook->getLoginUrl(
    array(
        'scope' => 'manage_pages'
    )
);

if ($user) {
    try {
        // Proceed knowing you have a logged in user who's authenticated.
        //$user_profile = $facebook->api('/me');
        $access_token = $facebook->getAccessToken();
        $graph_url = "https://graph.facebook.com/me/accounts?access_token="
        . $access_token;
        
        $accounts = json_decode(file_get_contents($graph_url));
        
    } catch (FacebookApiException $e) {
        //you should use error_log($e); instead of printing the info on browser
        d($e); // d is a debug function defined at the end of this file
        $user = null;
    }
}

if (!$user) {
    echo "<script type='text/javascript'>top.location.href = '$loginUrl';</script>";
    exit;
}

//print_r($user_profile);
print_r($accounts);

?>