<h1>Onglet1</h1>
<?php 

$fbconfig['appid' ] = "218054684985857";
$fbconfig['secret'] = "efa396557e4ced4c6b8e5dcf83cbef1f";

    $app_id = $fbconfig['appid' ];
    $app_secret = $fbconfig['secret'];
    $app_token_url = "https://graph.facebook.com/oauth/access_token?"
        . "client_id=" . $app_id
        . "&client_secret=" . $app_secret 
        . "&grant_type=client_credentials";

        $response = file_get_contents($app_token_url);
        $params = null;
    parse_str($response, $params);

    echo("This app's access token is: " . $params['access_token']);

    $graph_url = "https://graph.facebook.com/app?access_token="
    . $params['access_token'];
    
    $app_details = json_decode(file_get_contents($graph_url), true);
    
    echo("<br />Here is a link to the app " . $app_details['link']);
    
    print_r($app_details);
    
 ?>
 