<?php $container = $this->navigation()->breadcrumbs()  ?>
<?php /* @var $container \Zend\View\Helper\Navigation\Breadcrumbs */ ?>
<?php $navigation = $container->getContainer() ?>
<?php /* @var $navigation \Zend\Navigation\Navigation */ ?>

<ul class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><?php echo $this->translate('Home'); ?></a></li>
    <?php $active = $container->findActive($navigation) ?>
    <?php foreach($this->pages as $page): ?>
        <?php /* @var $page \Zend\Navigation\Page\Mvc */ ?>
        <?php if( ! $page->isActive()): ?>
            <li>
                <span class="divider">&nbsp;&gt;</span>
                <a href="<?php echo $page->getHref() ?>"><?php echo $page->getLabel() ?></a> 
            </li>
        <?php else: ?>
            <li class="active">
            	<span class="divider">&nbsp;&gt;</span>
                <?php if($container->getLinkLast()): ?>
                	<a href="<?php echo $page->getHref() ?>">
                <?php endif ?>
                <?php echo $page->getLabel() ?>
                <?php if($container->getLinkLast()): ?>
                	</a>
                <?php endif ?>
            </li>
        <?php endif ?>
    <?php endforeach ?>
</ul>